version: '3.5'
services:
  master:
    build:
      context: .
    image: pwnsky/squick:1.1
    user: root
    restart: always
    environment:
      - SQUICK_ARGS=type=master id=1 area=0 ip=172.0.1.1 port=10001 web_port=8888
    networks:
      squick_net:
        ipv4_address: 172.0.1.1

  world:
    build:
      context: .
    image: pwnsky/squick:1.1
    user: root
    restart: always
    environment:
      - SQUICK_ARGS=type=world id=100 area=0 ip=172.0.1.2 port=10101 master_ip=172.0.1.1 master_port=10001
    networks:
      squick_net:
        ipv4_address: 172.0.1.2

  db_proxy:
    build:
      context: .
    image: pwnsky/squick:1.1
    user: root
    restart: always
    environment:
      - SQUICK_ARGS=type=db_proxy id=300 area=0 ip=172.0.1.3 port=10201 master_ip=172.0.1.1 master_port=10001
    networks:
      squick_net:
        ipv4_address: 172.0.1.3

  web:
    build:
      context: .
    image: pwnsky/squick:1.1
    user: root
    restart: always
    ports:
      - 8080:80
    environment:
      - SQUICK_ARGS=type=web id=2 area=0 ip=172.0.1.4 port=10301 web_port=80 master_ip=172.0.1.1 master_port=10001
    networks:
      squick_net:
        ipv4_address: 172.0.1.4

  player:
    build:
      context: .
    image: pwnsky/squick:1.1
    user: root
    restart: always
    environment:
      - SQUICK_ARGS=type=player id=1000 area=0 ip=172.0.1.5 port=10401 master_ip=172.0.1.1 master_port=10001
    networks:
      squick_net:
        ipv4_address: 172.0.1.5

  proxy1:
    build:
      context: .
    image: pwnsky/squick:1.1
    user: root
    restart: always
    environment:
      - SQUICK_ARGS=type=proxy id=500 area=0 ip=172.0.1.6 port=10501 master_ip=172.0.1.1 master_port=10001
    networks:
      squick_net:
        ipv4_address: 172.0.1.6

  backstage:
    build:
      context: .
    image: pwnsky/squick:1.1
    user: root
    restart: always
    ports:
      - 8888:80
    environment:
      - SQUICK_ARGS=type=backstage id=10 area=0 ip=172.0.1.7 port=10401 web_port=80 master_ip=172.0.1.1 master_port=10001
    networks:
      squick_net:
        ipv4_address: 172.0.1.7

  db_mysql:
    build:
      context: .
    image: mysql:8.0
    user: root
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pwnsky_squick
    networks:
      squick_net:
        ipv4_address: 172.0.1.60

  db_mongo:
    build:
      context: .
    image: mongo:6.0.5
    user: root
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pwnsky_squick
    networks:
      squick_net:
        ipv4_address: 172.0.1.61

  db_clickhouse:
    build:
      context: .
    image: clickhouse/clickhouse-server:23.1.3.5-alpine
    user: root
    restart: always
    networks:
      squick_net:
        ipv4_address: 172.0.1.62

  db_redis:
    build:
      context: .
    image: redis:7.0
    user: root
    restart: always
    environment:
      - REDIS_PASSWORD=pwnsky_squick
    networks:
      squick_net:
        ipv4_address: 172.0.1.63

networks:
    default:
    internal:
        internal: true
    squick_net:
        ipam:
            config:
            - subnet: 172.0.1.0/16
