-- 玩家登录基本数据sql

-- 表的结构 `app_users`

DROP TABLE IF EXISTS `account`;
CREATE TABLE `app_users` (
  `id`  BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `uuid` VARCHAR(127) NOT NULL COMMENT '用户uuid',
  `nickname` VARCHAR(127) NOT NULL DEFAULT '' COMMENT '昵称',
  `header_image` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '头像URL',
  `email` VARCHAR(127) NOT NULL DEFAULT '' COMMENT '邮箱',
  `phone_number` VARCHAR(31) NOT NULL DEFAULT '' COMMENT '手机号',
  `password` VARCHAR(127) NOT NULL DEFAULT '' COMMENT '密码HASH',
  `name` VARCHAR(127) NOT NULL DEFAULT '' COMMENT '姓名',
  `idn` VARCHAR(127) NOT NULL DEFAULT '' COMMENT '身份证号',
  `gender` INT(8) NOT NULL DEFAULT '0' COMMENT '性别： 0 未设定， 1，男 2 女',
  `ctime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '注册时间',
  `ltime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后登录时间',
  `wechat_openid` VARCHAR(127) NOT NULL DEFAULT '' COMMENT '微信openid',
  PRIMARY KEY (`id`),
  KEY `uuid` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


DROP TABLE IF EXISTS `wechat_login`;
CREATE TABLE `app_users_wechat` (
  `id`  BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `uuid` VARCHAR(127) NOT NULL COMMENT '用户uuid', -- uuid
  `openid` VARCHAR(127) NOT NULL DEFAULT '' COMMENT '昵称',
  `scope` VARCHAR(127) NOT NULL DEFAULT '' COMMENT '头像URL',
  `unionid` VARCHAR(127) NOT NULL DEFAULT '' COMMENT 'UnionID',
  `access_token` VARCHAR(127) NOT NULL DEFAULT '' COMMENT 'UnionID',
  `refresh_token` VARCHAR(127) NOT NULL DEFAULT '' COMMENT 'UnionID',
  `atime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '授权时间',
  PRIMARY KEY (`id`),
  KEY `uuid` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
