---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backstage
  namespace: default
  labels:
    app: squick
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squick
  template:
    metadata:
      labels:
        app: squick
    spec:
      containers:
        - name: squick
          image: pwnsky/squick:1.2
          imagePullPolicy: Never
          command: ["/bin/bash", "-c"]
          args:
            - >
              /squick/script/squick.sh type=backstage id=`expr 2500 + ${HOSTNAME##*-}` area=0 ip=$(POD_IP) port=10501 ws_port=10502 master_ip=svc-squick-master master_port=10001 logshow=0
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
