name: Github-CI

on: [push, pull_request]

jobs:
  build_third_party:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Updating submodule
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest' || matrix.os == 'windows-latest'
        run: |
          git submodule update --init
          
      - name: Building squick third party library for linux and macos
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
        run: |
          cd tools && ./build_third_party.sh
      
      - name: Building squick third party library for windows
        if: matrix.os == 'windows-latest'
        run: |
          cd tools
          .\clone_thirdparty_build.bat no_pause
          
      - name: Building sqkctl tools for linux and macos
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
        run: |
          cd res/ToolsSrc/sqkctl && ./build.sh

      - name: Building sqkctl tools for windows
        if: matrix.os == 'windows-latest'
        run: |
          cd res\ToolsSrc\sqkctl
          .\build.bat no_pause
          
      - name: Building squick project for linux and macos
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
        run: |
          cd tools && ./build.sh
          
      - name: Building squick project for windows
        if: matrix.os == 'windows-latest'
        run: |
          cd tools
          .\build.bat no_pause
          
      - name: Geneating deploy files for linux and macos
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
        run: |
          cd tools && ./gen_deploy.sh
          cd ../deploy
          ls -al
          
      - name: Geneating deploy files for windows
        if: matrix.os == 'windows-latest'
        run: |
          cd tools
          .\gen_deploy.bat no_pause
          cd ..\deploy
          dir