name: Github-CI

on: [push, pull_request]

jobs:
  build_third_party:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Building squick third party lib
        if: matrix.os == 'ubuntu-20.04' || matrix.os == 'macOS-latest'
        run: |
          cd tools && ./build_third_party.sh
      
      - name: Building squick third party lib
        if: matrix.os == 'windows-latest'
        run: |
          cd tools
          .\clone_thirdparty_build.bat
          
      - name: Building squick tools
        if: matrix.os == 'ubuntu-20.04' || matrix.os == 'macOS-latest'
        run: |
          cd tools && ./build_sqkctl.sh

      - name: Building squick tools
        if: matrix.os == 'windows-latest'
        run: |
          cd tools
          .\build_sqkctl.bat
          
      - name: Building squick
        if: matrix.os == 'ubuntu-20.04' || matrix.os == 'macOS-latest'
        run: |
          cd tools && ./build_squick.sh
          
      - name: Building squick
        if: matrix.os == 'windows-latest'
        run: |
          cd tools
          .\build_squick.bat
          
      - name: Geneating deploy files
        if: matrix.os == 'ubuntu-20.04' || matrix.os == 'macOS-latest'
        run: |
          cd tools && ./generate_deploy.sh

      - name: Geneating deploy files
        if: matrix.os == 'windows-latest'
        run: |
          cd tools
          .\generate_deploy.bat

