name: Github-CI

on: [push, pull_request]

jobs:
  build_third_party:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Building squick third party library
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd tools && ./build_third_party.sh
        if: matrix.os == 'macOS-latest'
        run: |
          cd tools && ./build_third_party.sh
        if: matrix.os == 'windows-latest'
        run: |
          cd tools
          .\clone_thirdparty_build.bat
      
      - name: Building sqkctl tools
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd tools && ./build_sqkctl.sh
        if: matrix.os == 'macOS-latest'
        run: |
          cd tools && ./build_sqkctl.sh
        if: matrix.os == 'windows-latest'
        run: |
          cd tools
          .\build_sqkctl.bat
                
      - name: Building squick project
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd tools && ./build_squick.sh
        if: matrix.os == 'macOS-latest'
        run: |
          cd tools && ./build_squick.sh
        if: matrix.os == 'windows-latest'
        run: |
          cd tools
          .\build_squick.bat

      - name: Geneating deploy files
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd tools && ./generate_deploy.sh
          cd ../deploy
          tree
        if: matrix.os == 'macOS-latest'
        run: |
          cd tools && ./generate_deploy.sh
        if: matrix.os == 'windows-latest'
        run: |
          cd tools
          .\generate_deploy.bat